### ISSUE TITLE
FireBug console inaccessible after it is opened externally and then closed

### ISSUE THREAD

**Issue by MIchaelMainer** [OfficeDev/script-lab-2017#208]
Repro: 
1) Open FireBug in New Window
2) Close Window.
3) Select the FireBug icon, it doesn't reopen. 

It would be great if OnBeforeUnload for the new FireBug, it returned the FireBug console back to the state it was in the task pane.

**Comment by Zlatkovsky** [comment]
Not relevant anymore in the React version of Script Lab, since we don't use Firebug anymore.
