### ISSUE TITLE
Pop-out Editor (especially for Mac and Office Online)

### ISSUE THREAD

**Issue by saunders77** [OfficeDev/script-lab-2017#277]
Today, esp. on Online, you can have a super-awesome editing experience by launching https://script-lab.azureedge.net, selecting your host, and being able to edit there while running inside the actual Office Online instance.

We could also do similar with a dialog API, which would make it work on the MAC as well.

Actual work is pretty trivial, but need a UX design.

**Comment by Zlatkovsky** [comment]
@jakobpn , @danielmgalan , adding you for the UX design

**Comment by Zlatkovsky** [comment]
Isn't strictly about sharing per se... but makes experience much nicer, if opening on office online, which might become increasingly common with sharing.

**Comment by Zlatkovsky** [comment]
As for the UX design, probably just a pop-out button on very top right.

**Comment by Zlatkovsky** [comment]
@annich-MS , adding you as well, since outlook will need this, and since we discussed it on the phone a week or two ago

**Comment by Zlatkovsky** [comment]
Done in the React version of Script Lab.
