### ISSUE TITLE
Unable to sign in to GitHub in Excel Online

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab-2017#624]
## Current Behavior

Script Lab opens a browser windows and asks for host

## Steps to Reproduce (for bugs)

1. Open Script Lab in Excel Online
2. Click Sign In to Github
3. Click Allow to the dialog that comes up
4. 

## Your Environment

* Version used: Alpha
* Browser Name and version: Edge
* Operating System and version (desktop or mobile): Windows 10

![image](https://user-images.githubusercontent.com/13109307/30568906-9e55ab9e-9c8c-11e7-8dd7-e2baa38288b9.png)

![image](https://user-images.githubusercontent.com/13109307/30568915-aaa5377a-9c8c-11e7-8c22-80a60b75dc28.png)

## Useful logs

- [ ] Fiddler traces
- [ ] Console errors
- [ ] Screenshots
- [ ] Clip or GIFs

**Comment by Zlatkovsky** [comment]
It's a platform issue.
Interestingly, @jakobpn, it looks like it only happened on your machine, even with the Microsoft sharepoint site.  Kim also used her work one, and also got the first prompt saying that "we'll need to pop up a separate window", but the rest of the flow worked for her.

**Comment by Zlatkovsky** [comment]
Actually, might still be a bug on my end.  Or at least, I have a (possibly different) issue when just signing in via the web.
let me get back to you once it's resolved, and we can then try to have you repro.

**Comment by Zlatkovsky** [comment]
@jakobpn, never mind my last comment.  My issue was another and unrelated issue  (https://github.com/OfficeDev/office-js-helpers/issues/50).  Which means that what you were seeing is still a platform issue, that you should still route to the platform.

**Comment by Zlatkovsky** [comment]
The auth flow has been reworked in the new React-based Script Lab.  Closing.
