### ISSUE TITLE
[Editor performance]: Split out snippets into individual localStorage entries

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab-2017#709]
Right now, all snippets are stored in the very same setting (one per host) in stirngified JSON form.  Moreover, typing any code causes a (debounced) update that both reads the existing content, parses it, merges with the new, and then stringifies and saves the result.  Once every 250 ms.

I am not sure if it's causing perf issues yet or not... But I continue to think that a more scaleable approach would have been to have a single master file for just the ordering of snippets, and then have each individual snippet be an entry.

**Comment by WrathOfZombies** [comment]
@Zlatkovsky incoming enhancement via `OfficeHelpers`

**Comment by Zlatkovsky** [comment]
Due to issues that we were having with refresh/heartbeat on desktop (https://github.com/OfficeDev/script-lab/pull/761/files), there is now some code that modifies the snippets localstorage directly.  So, this should be taken into account.

**Comment by Zlatkovsky** [comment]
Fixed in the Script Lab React repo.
