### ISSUE TITLE
Script Lab doesn't work with Project (regression)

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab-2017#808]
![image](https://user-images.githubusercontent.com/2230453/39637155-0f628724-4f77-11e8-82e5-28eb3b22f9f1.png)

**Comment by nico-bellante** [comment]
@Zlatkovsky is this a dupe of #733 ?

**Comment by Zlatkovsky** [comment]
It is indeed a dup.  Closing.
