### ISSUE TITLE
Feature: Permanently save snippets

### ISSUE THREAD

**Issue by Allexxann** [OfficeDev/script-lab-2017#864]
It would be good to have an ability to save my library of custom snippets on disk without importing and exporting them manually each and every time - either in user-specified folder or just in scriptlab itself, doesn't matter.
Reason: sometimes I have no internet access for months on my main machine, and I don't want to worry about remembering, should I exclude browser cache from regular clean-up or not.

Same goes for dependencies, especially for office.js/office.ts - should you pass special parameter for them, then system downloads them on the first run and stashes somewhere and on subsequent runs only updates libraries, if any updates are present.
Well, maybe feature like this is already present, but I couldn't find it then.

And, of course, you'd need "delete" button for them too.

**Comment by Zlatkovsky** [comment]
Yes, more permanent storage is definitely on the backlog.
Re. being able to truly be offline -- that one is tougher.  In the short-term, I don't imagine us being able to invest in this, but it's certainly something we're aware we could need longer-term.

**Comment by sancarn** [comment]
@Zlatkovsky theoretically could we host script-lab server locally, perhaps in a COM add-in? I guess a more permanent solution would be to use a service worker but currently IE doesn't support them.

**Comment by Zlatkovsky** [comment]
@sancarn , it depends on what you are trying to achieve (and/or whether you're just asking this for in a purely theoretical sense).  Is your question related to downloading, or to off-lining in general?

**Comment by sancarn** [comment]
@Zlatkovsky it was about offlining in general. It may be the easiest option to make purely offline script-lab possible...

**Comment by Allexxann** [comment]
>  It may be the easiest option to make purely offline script-lab possible...

Sounds ideally for me.

**Comment by Zlatkovsky** [comment]
Right now, add-ins require an internet connection.  You might be able to host Script Lab locally to sidestep that (though even so, Script Lab today relies on the internet for it's IntelliSense/autocomplete in the editor, and on its samples list, etc.) so while it's _technically_ possible, it's not really set up for it right now.  Like I said, it's something we'll keep in mind for the future.  You can try to self-host using the steps on https://github.com/OfficeDev/script-lab/blob/master/CONTRIBUTING.md (and I *had* made some changes a few months ago, https://github.com/OfficeDev/script-lab/commit/933437c16b1b1b3e7cf7ed26e96acb47f81ea535, to make offline development possible), but mileage will vary...

Are interested in this just from the angle of making just Script Lab work for you offline, or from the angle of making *your own add-ins be able to be offline-able*?  If it's the latter, you are welcome to add a comment to https://officespdev.uservoice.com/ to voice your support/requirements for offline add-ins...

**Comment by Zlatkovsky** [comment]
We have fully re-worked Script Lab, re-writing it from scratch using a new UI framework in a newer repo.  See more at https://developer.microsoft.com/en-us/office/blogs/announcing-script-lab-react/.

I am going through and consolidating issues across the two repos.  I'll go ahead and close the issue on this side, since any future work will be happening in the new repo.  The new issue tracking it is at https://github.com/OfficeDev/script-lab/issues/526
