### ISSUE TITLE
Use ChromeConsole.js instead of FireBug console!

### ISSUE THREAD

**Issue by sancarn** [OfficeDev/script-lab-2017#881]
Firebug is great when it comes to the DOM, don't get me wrong! But it's console is awful! I'd suggest using chromeConsole.js:

[Demo](https://tarvk.github.io/chromeConsole/About.html)

[Git Repository](https://github.com/TarVK/chromeConsole)

**Comment by Zlatkovsky** [comment]
Thanks for suggesting it, I wasn't aware of the project.  We have been considering doing some revamping of the console experience for some time, I'll add this to the list of possible things to consider.

**Comment by Zlatkovsky** [comment]
In the new Script Lab React repo, we've just added it in https://github.com/OfficeDev/script-lab/pull/612, using the "react-inspector" NPM package (https://www.npmjs.com/package/react-inspector).
Closing as fixed (in the other repo).
