### ISSUE TITLE
Using lodash.throttle in snippet

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab-2017#884]
Trying to use lodash.throttle function in a Script Lab snippet.

I have included these lines in the Library tab:
lodash
@types/lodash

## Expected Behavior
Script Lab would be able to recognize _.throttle() and not display an error message.

## Current Behavior
_.throttle is marked with a red squiggle with the error "Property throttle does not exist on type LoDashStatic". 

The code function as expected.

https://gist.github.com/f666b39575fe701700e5672f7c8e5253

![image](https://user-images.githubusercontent.com/13109307/48599524-debbb600-e91c-11e8-84ff-92d47355fea5.png)

## Your Environment

* Version used: Excel build 11113
* Browser Name and version:
* Operating System and version (desktop or mobile): Windows

**Comment by Zlatkovsky** [comment]
Closing this issue, in lieu of the one on the new repo (https://github.com/OfficeDev/script-lab/issues/337)
