### ISSUE TITLE
Cannot authorize my github in Windows10 Desktop App?

### ISSUE THREAD

**Issue by sancarn** [OfficeDev/script-lab-2017#887]
See image below:

![image](https://user-images.githubusercontent.com/7938900/49321420-44a06400-f4ff-11e8-8736-89bf7f3ed30e.png)

The "Authorize office js" button never enables...?
Also the grey dropdown button appears to be clickable but clicking on it does nothing...?

This seems to be independant of zoom.

**Comment by Zlatkovsky** [comment]
@sancarn , sorry to hear you're seeing this issue.  We've recently discovered that this has started happening, and will be making a fix soon.

In the meantime, one workaround is for you to go to <https://script-lab.azureedge.net/?host=EXCEL> from a *non-IE* browser and click "sign in" there.  Once you've signed in, close the browser, and try signing in from within Office again.  It should bypass this page and succeed.

Let us know if you're still having issues.  Will keep this issue active for now for tracking

**Comment by sancarn** [comment]
Will give the workaround a go. Cheers!

**Comment by Zlatkovsky** [comment]
Now that we have a new React-based Script Lab codebase which is our main one going forward, we'll be making a fix there rather than here.

Closing this issue as a dup of https://github.com/OfficeDev/script-lab/issues/248.
