### ISSUE TITLE
How does one compile an Addin to a Content Addin?

### ISSUE THREAD

**Issue by sancarn** [OfficeDev/script-lab-2017#889]
I initially expected to simply change the:

```
<OfficeApp
          ...
          xsi:type="TaskPaneApp">
```
in the manifest to
```
<OfficeApp
          ...
          xsi:type="ContentApp">
```
However this doesn't appear to be correct as office is refusing to see my content addin...?

----

Note: 

I simply published a blank-snippet to a shared folder and changed `TaskPaneApp` to `ContentApp`.

**Comment by Zlatkovsky** [comment]
@sancarn , did you meant to ask this question on StackOverflow (and/or on the office-js repo -- though really, StackOverflow with an "[office-js]" tag seems like the most appropriate place).

Either way, this doesn't look Script Lab-specific.

**Comment by sancarn** [comment]
Hi @Zlatkovsky, sorry for the misunderstanding. It was specifically about publishing the add-in using  script-lab's publish feature. How does one publish a script as a content-addin instead of a TaskPaneApp?

**Comment by Zlatkovsky** [comment]
Oh, I see.  I didn't realize you were publishing the snippet.  I just changed the title to reflect that.

To be honest, publishing is actually one of the few features that we've not ported over from "old" Script Lab to the new one yet.  We have a bug tracking it at https://github.com/OfficeDev/script-lab/issues/62.  I added a note that we should consider allowing the option of taskpane vs content as well.

To answer your question, there are probably a few other required settings (e.g., width and height).  From <https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-2>, here is what the manifest should look like:

```
<?xml version="1.0" encoding="utf-8"?>
<OfficeApp
  xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:type="ContentApp">
  <Id>01eac144-e55a-45a7-b6e3-f1cc60ab0126</Id>
  <AlternateId>en-US\WA123456789</AlternateId>
  <Version>1.0.0.0</Version>
  <ProviderName>Microsoft</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Sample content add-in" />
  <Description DefaultValue="Describe the features of this app." />
  <IconUrl DefaultValue="https://contoso.com/assets/icon-32.png" />
  <HighResolutionIconUrl DefaultValue="https://contoso.com/assets/hi-res-icon.png" />

  <SupportUrl DefaultValue="[Insert the URL of a page that provides support information for the app]" />

  <Hosts>
    <Host Name="Workbook" />
    <Host Name="Database" />
  </Hosts>
  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="TableBindings" />
    </Sets>
  </Requirements>  
  <DefaultSettings>
    <SourceLocation DefaultValue="https://contoso.com/apps/content.html" />
    <RequestedWidth>400</RequestedWidth>
    <RequestedHeight>400</RequestedHeight>
  </DefaultSettings>
  <Permissions>Restricted</Permissions>
  <AllowSnapshot>true</AllowSnapshot>
</OfficeApp>
```

**Comment by sancarn** [comment]
I forgot to mention that I had actually figured out the minimal requirements for an add-in (at least a content add-in) displayed in some [example code I made](https://github.com/sancarn/xlTextBox/blob/master/textBox.xml):

```
<!--
  Addins minimally require:
  * <?xml version="1.0" encoding="UTF-8"?> at the top of the document.
  * <OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"  xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:type="ContentApp">
  * AppDomain      (can be anything)
  * SourceLocation (MUST BE A VALID URL which doesn't return http error code. Can be a file:/// url also)
  * ProviderName   (can be anything)
  * DefaultLocale  (can be anything)
  * DisplayName     (can be anything)
  * Description    (can be anything)
  * Permissions    (can be anything)
  * ID?            (Untested: Should be unique)
-->
``` 

And thus a valid (but terrible) manifest would be:

```
<OfficeApp 
    xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" 
    xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" 
    xsi:type="ContentApp">
    
  <Id>c6890c26-5bbb-40ed-a321-37f07909a2f0</Id>
  <Version>1.0</Version>
  <ProviderName>.</ProviderName>
  <DefaultLocale>.</DefaultLocale>
  <DisplayName DefaultValue="." />
  <Description DefaultValue="."/>
  <AppDomains><AppDomain>.</AppDomain></AppDomains>
  <DefaultSettings>
      <SourceLocation DefaultValue="file:///\\mycloudex2ultra\public\MsoAddins\textBox.html" />
  </DefaultSettings>
  <Permissions>.</Permissions>
</OfficeApp>
```

**Comment by kbrandl** [comment]
@sancarn you can find an example "Content add-in" manifest documented here in the Office Add-ins documentation: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?view=office-js&tabs=tabid-2#manifest-v11-xml-file-examples-and-schemas.
